# Critical Error Detection Configuration

# Model Configuration
model:
  name: "distilbert-base-multilingual-cased"
  max_seq_length: 512
  num_labels: 2

# Training Configuration
training:
  batch_size: 16
  learning_rate: 2.0e-5
  num_epochs: 3
  weight_decay: 0.01
  warmup_steps: 500

# Data Configuration
data:
  train_data_dir: "data/catastrophic_errors"
  gold_labels_dir: "data/catastrophic_errors_goldlabels"
  train_ratio: 0.8
  val_ratio: 0.1
  random_seed: 42
  num_workers: 0
  pin_memory: false

# Output Paths
paths:
  checkpoints_dir: "results/checkpoints"
  logs_dir: "logs"
  results_dir: "results"

# Logging
logging:
  level: "INFO"
  log_interval: 100
